### ISSUE TITLE
reduce duplicate `vim-script` content - autoclosed

### ISSUE THREAD

**Issue by LucasLarson** [LucasLarson/dotfiles#597]
Vim uses `~/.vimrc` according to @HiPhish¹, whereas Neovim uses `$XDG_CONFIG_HOME/init.vim`

this repository:
- uses both, and
- contains almost-identical files²

---
1. [reddit.com/comments/vp78ug](https://old.reddit.com/comments/vp78ug/_/iehk8bp)
2. [LucasLarson/dotfiles/search (language: `vim-script`)](https://web.archive.org/web/20220823155640/https://github.com/LucasLarson/dotfiles/search?l=vim-script) as of 2022-08-23

**Comment by HiPhish** [comment]
Just a little advice for the future: when you tag someone with `@` he will become subscribed to the issue and get notifications. I was really surprised when seven emails popped up in my account all of the sudden.

I am not angry or anything, beginner mistakes happen. Just something to keep in mind.

**Comment by LucasLarson** [comment]
Yikes — but thanks for the encouragement and direction!
